### ISSUE TITLE
An error while building MMTK: `fatal error: Scientific/netcdfmodule.h: No such file or directory`

### ISSUE THREAD

**Issue by igorsdub** [khinsen/MMTK#1]
#### Description
Dear MMTK maintainers,

I am attempting to create a Dockerfile that builds an image for MMTK.
So far, I have managed to install all dependencies mentioned in the MMTK `README.md`.
However, I could not install MMTK, not even build it.

When I run `python setup.py build` in `/root/code/MMTK` I get this error (the full log is available at the end of this post):
```bash
Include/MMTK/trajectory.h:12:37: fatal error: Scientific/netcdfmodule.h: No such file or directory
compilation terminated.
In file included from Src/MMTK_DCD.c:8:0:
Include/MMTK/trajectory.h:12:37: fatal error: Scientific/netcdfmodule.h: No such file or directory
compilation terminated.
error: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DLIBM_HAS_ERFC -D_LONG64_ -DEXTENDED_TYPES -IInclude -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c Src/MMTK_DCD.c -o build/temp.linux-x86_64-2.7/Src/MMTK_DCD.o -DNUMPY=1" failed with exit status 1
```
#### Python Packages
```bash
$ pip list
numpy (1.6.0)
pip (8.1.1)
ScientificPython (2.9.4)
setuptools (20.7.0)
wheel (0.29.0)
You are using pip version 8.1.1, however version 20.3.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Nore. I have tried installing `ScientificPython` via `pip` as well, but it made no difference.
Also, `NumPy 1.8.0` made no difference.
#### NetCDF
Indeed, I was not able to locate `netcdfmodule.h` in `/usr/local/lib/python2.7/dist-packages/Scientific`, but I have netCDF installed to the image:
```bash
$ nc-config --all

This netCDF 4.4.0 has been built with the following features: 

  --cc        -> /usr/bin/x86_64-linux-gnu-gcc
  --cflags    -> -I/usr/include -I/usr/include/hdf5/serial
  --libs      -> -L/usr/lib -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lnetcdf -lhdf5_hl -lhdf5 -lpthread -lsz -lz -ldl -lm -lcurl

  --has-c++   -> no
  --cxx       -> 
  --has-c++4  -> no
  --cxx4      -> 

  --fc        -> 
  --fflags    -> 
  --flibs     -> 
  --has-f90   -> no

  --has-dap   -> yes
  --has-nc2   -> yes
  --has-nc4   -> yes
  --has-hdf5  -> yes
  --has-hdf4  -> no
  --has-pnetcdf-> no
  --has-szlib -> no

  --prefix    -> /usr
  --includedir-> /usr/include
  --version   -> netCDF 4.4.0
```
##### Dockerfile for MMTK

```dockerfile
FROM ubuntu:16.04

LABEL Igors Dubanevics <igordub@github.com>

# Set the working directory in the container
WORKDIR /root/code

# Updates cache
# Without this command no packages can be installed
RUN apt-get update && apt-get -y upgrade

# Install packages
RUN apt-get install -y \
    git \
    python \
    python-pip \
    libhdf5-serial-dev \
    netcdf-bin \
    libnetcdf-dev

# Install dependencies
RUN pip install numpy==1.6.0

# Download ScientificPyhton and MMTK from GitHub
RUN git clone https://github.com/khinsen/ScientificPython.git
RUN git clone https://github.com/khinsen/MMTK.git

# Move to ScientificPython dir
WORKDIR /root/code/ScientificPython

# Build and install ScientificPython package
RUN python setup.py build
RUN python setup.py install 

# Move out to the main working dir
WORKDIR /root/code/
```

###### Running Dockerfile
In order to build the image, run:
```bash
docker build -t mmtk:build Dockerfile <path-to-Dockerfile>
docker run -it mmtk:build /bin/bash
```
Inside the container, run:
```bash
$ cd MMTK
$ python setup.py build
```

**Comment by khinsen** [comment]
If you don't have `netcdfmodule.h` in your installation of ScientificPython, then the installation script of ScientificPython has not found your netCDF. You should see a warning about this in your logs. If everything goes well, the same logs should contain a line of the form "Using netCDF installation in ...". So this is the first thing to check - MMTK won't build if ScientificPython is incomplete.

By default, ScientificPython checks `/usr` and `/usr/local` for the presence of `include/netcdf.h`. You can set the environment variable `NETCDF_PREFIX` to indicate another location, e.g. `NETCDF_PREFIX=/opt/local`.
```
```

**Comment by igorsdub** [comment]
@khinsen Thank you for the prompt reply.

During ScientificPython installation, this script finds netCDF module in the container:

```bash
$ python setup.py build 
Using netCDF installation in  /usr
running build
running build_py
running build_ext
running build_scripts
$ python setup.py install
Using netCDF installation in  /usr
running install
running build
running build_py
running build_ext
running build_scripts
running install_lib
running install_headers
running install_scripts
changing mode of /usr/local/bin/task_manager to 755
changing mode of /usr/local/bin/bsp_virtual to 755
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/ScientificPython-2.9.4.egg-info
```
And, I've checked that `/usr/include/netcdf.h` does exists. It still gives the same error while building MMTK.

#### Update
There is another error that is thrown out when I try to install ScientificPython via `pip`:
```bash
$ pip install ScientificPython
Collecting ScientificPython
Installing collected packages: ScientificPython
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 375, in move_wheel_files
    dest = scheme[subdir]
KeyError: 'Scientific'
```
This error does not appear when I install the package from GitHub.

#### MMTK error
```bash
$ python setup.py build 
running build
running build_py
running build_ext
building 'MMTK.linux2.MMTK_DCD' extension
C compiler: x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC

compile options: '-DLIBM_HAS_ERFC -D_LONG64_ -DEXTENDED_TYPES -IInclude -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c'
extra options: '-DNUMPY=1'
x86_64-linux-gnu-gcc: Src/MMTK_DCD.c
In file included from Src/MMTK_DCD.c:8:0:
Include/MMTK/trajectory.h:12:37: fatal error: Scientific/netcdfmodule.h: No such file or directory
compilation terminated.
In file included from Src/MMTK_DCD.c:8:0:
Include/MMTK/trajectory.h:12:37: fatal error: Scientific/netcdfmodule.h: No such file or directory
compilation terminated.
error: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DLIBM_HAS_ERFC -D_LONG64_ -DEXTENDED_TYPES -IInclude -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c Src/MMTK_DCD.c -o build/temp.linux-x86_64-2.7/Src/MMTK_DCD.o -DNUMPY=1" failed with exit status 1
```

You can easily reproduce this issue by using the `Dockerfile` I've attached to the first post.
Thank you.

**Comment by khinsen** [comment]
I did a quick check: it's the old Linux packaging issue. First, the solution:
```
cd MMTK
ln -s /usr/local/include/python2.7/Scientific Include/
python setup.py build
```

Explanation: some Linux distribution patch Python in such a way that its binaries and standard library are under `/usr`, whereas add-ons get installed to `/usr/local`. That breaks all packages that come with C extensions that use the CObject protocol. And that includes ScientificPython and MMTK. There are other possible fixes than the one above, e.g. adding `/usr/local/include/python2.7/` to the compiler's search path for header files.

**Comment by igorsdub** [comment]
Yes, that worked!
```bash
$ pip list
MMTK (2.7.12)
numpy (1.6.0)
pip (8.1.1)
ScientificPython (2.9.4)
setuptools (20.7.0)
wheel (0.29.0)
```
For the Dockerfile, I will include your suggestion about adding the search path.

#### Yet, another issue
Now, I cannot import MMTK in Python.
```bash
$ python
Python 2.7.12 (default, Oct  5 2020, 13:56:01) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from MMTK import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "MMTK/__init__.py", line 47, in <module>
    from ThreadManager import activeThreads, waitForThreads
  File "MMTK/ThreadManager.py", line 38, in <module>
    import MMTK_state_accessor
ImportError: No module named MMTK_state_accessor
>>> 
```
Thank you, again.

**Comment by khinsen** [comment]
Works for me! Here is the complete Dockerfile I used:

```
FROM ubuntu:16.04

LABEL Igors Dubanevics <igordub@github.com>

# Set the working directory in the container
WORKDIR /root/code

# Updates cache
# Without this command no packages can be installed
RUN apt-get update && apt-get -y upgrade

# Install packages
RUN apt-get install -y \
    git \
    python \
    python-pip \
    libhdf5-serial-dev \
    netcdf-bin \
    libnetcdf-dev

# Install dependencies
RUN pip install numpy==1.6.0

# Download ScientificPyhton and MMTK from GitHub
RUN git clone https://github.com/khinsen/ScientificPython.git
RUN git clone https://github.com/khinsen/MMTK.git

# Move to ScientificPython dir
WORKDIR /root/code/ScientificPython

# Build and install ScientificPython package
RUN python setup.py build
RUN python setup.py install 

# Move to MMTK dir
WORKDIR /root/code/MMTK

# Add a link to the ScientificPython Include directory,
# to work around the package installation patch in Ubuntu 16.04.
RUN ln -s /usr/local/include/python2.7/Scientific Include/

# Build and install MMTK package
RUN python setup.py build
RUN python setup.py install 

# Move out to the main working dir
WORKDIR /root/code/
```

In the resulting image, I can import MMTK without any error message.

**Comment by igorsdub** [comment]
Cheers, it works!
@khinsen, thank you for your time.

The only difference between your Dockerfile and mine was that I installed the dependencies, in this case, Numpy, form a file and, afterwards, used `ln -s /usr/local/include/python2.7/Scientific Include/` interactively inside the image.

Now, as it works, I will upload this file to the Docker Hub for others to use.
